export type ColorOption = { value: string; label: string; hex: string };

export const ALL_COLORS: ColorOption[] = [
  { value: "white", label: "Vit", hex: "#ffffff" },
  { value: "black", label: "Svart", hex: "#000000" },
  { value: "gray",  label: "Grå",  hex: "#9ca3af" },
  { value: "red",   label: "Röd",  hex: "#ef4444" },
  { value: "orange",label: "Orange", hex: "#fb923c" },
  { value: "yellow",label: "Gul",  hex: "#ffd700" },
  { value: "green", label: "Grön", hex: "#22c55e" },
  { value: "blue",  label: "Blå",  hex: "#3b82f6" },
  { value: "purple",label: "Lila", hex: "#8b5cf6" },
  { value: "army", label: "Militärgrön", hex: "#006400" },
  { value: "navy", label: "Navyblå", hex: "#000080" },
  { value: "brown", label: "Brun", hex: "#8B4513" },
  { value: "pink", label: "Rosa", hex: "#ffc0cb" },
  { value: "gold", label: "Guld", hex: "#f59e0b" },
  { value: "silver", label: "Silver", hex: "#c0c0c0" },
  { value: "bronze", label: "Brons", hex: "#cd7f32" },
  { value: "copper", label: "Koppar", hex: "#D2691E" },
  { value: "pearl", label: "Pärlgrå", hex: "#d3d3d3" },
  { value: "light-gray", label: "Ljusgrå", hex: "#d1d5db" },
  { value: "trans", label: "Transparent", hex: "#eeeeee" },
  { value: "natural", label: "Naturlig", hex: "#f5f5f5" },
  { value: "stone", label: "Sten", hex: "#d1d5db" },
  { value: "wood", label: "Trä", hex: "#DEB887" },
  { value: "aurora", label: "Aurora", hex: "#20B2AA" },
  { value: "sapphire", label: "Safirblå", hex: "#191970" },
  { value: "oxidizedcopper", label: "Oxidiserad koppar", hex: "#008B8B" },
  { value: "rainbow", label: "Regnbåge", hex: "#ff00ff" }, // multicolor filaments
  { value: "galaxy", label: "Galaxy", hex: "#1a1a40" }, // often dark + glitter
  { value: "sparkle-silver", label: "Glittersilver", hex: "#dcdcdc" },
  { value: "sparkle-gold", label: "Glitterguld", hex: "#ffd700" },
  { value: "ivory", label: "Elfenben", hex: "#fffff0" },
  { value: "burgundy", label: "Vinröd", hex: "#800020" },
  { value: "mustard", label: "Senapsgul", hex: "#ffdb58" },
  { value: "mint", label: "Mintgrön", hex: "#98ff98" },
  { value: "emerald", label: "Smaragdgrön", hex: "#50c878" },
  { value: "teal", label: "Teal", hex: "#008080" },
  { value: "skyblue", label: "Himmelsblå", hex: "#87ceeb" },
  { value: "lavender", label: "Lavendel", hex: "#e6e6fa" },
  { value: "coral", label: "Korall", hex: "#ff7f50" },
  { value: "neon-green", label: "Neongrön", hex: "#39ff14" }
];
